/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/action-popup/': RouteRecordInfo<'/action-popup/', '/action-popup', Record<never, never>, Record<never, never>>,
    '/action-popup/connect-ehr': RouteRecordInfo<'/action-popup/connect-ehr', '/action-popup/connect-ehr', Record<never, never>, Record<never, never>>,
    '/action-popup/enter-credential': RouteRecordInfo<'/action-popup/enter-credential', '/action-popup/enter-credential', Record<never, never>, Record<never, never>>,
    '/action-popup/select-clinic': RouteRecordInfo<'/action-popup/select-clinic', '/action-popup/select-clinic', Record<never, never>, Record<never, never>>,
    '/action-popup/select-sync': RouteRecordInfo<'/action-popup/select-sync', '/action-popup/select-sync', Record<never, never>, Record<never, never>>,
    '/action-popup/skip-page': RouteRecordInfo<'/action-popup/skip-page', '/action-popup/skip-page', Record<never, never>, Record<never, never>>,
    '/action-popup/welcome-login': RouteRecordInfo<'/action-popup/welcome-login', '/action-popup/welcome-login', Record<never, never>, Record<never, never>>,
    '/devtools-panel/': RouteRecordInfo<'/devtools-panel/', '/devtools-panel', Record<never, never>, Record<never, never>>,
    '/side-panel/': RouteRecordInfo<'/side-panel/', '/side-panel', Record<never, never>, Record<never, never>>,
  }
}
